repos:
- repo: local
  hooks:
    - id: clang-format
      name: clang-format
      entry: clang-format
      language: system
      files: \.(c|h)$
      args: ['-i']

    - id: clang-tidy
      name: clang-tidy
      entry: bash -c 'for file in "$@"; do clang-tidy "$file" --header-filter=.* -- -Iinc; done' --
      language: system
      files: ^src/.*\.(c)$

    - id: cppcheck
      name: cppcheck
      entry: cppcheck
      language: system
      files: \.(c|h)$
      args:
        - --enable=warning,style,performance,portability
        - --std=c11
        - --inline-suppr
        - --error-exitcode=1
        - -I
        - inc

    - id: trailing-whitespace
      name: trim trailing whitespace
      entry: sed -i 's/[[:space:]]*$//'
      language: system
      files: \.(c|h|yml|yaml|md)$

    - id: end-of-file-fixer
      name: fix end of files
      entry: bash -c 'for file in "$@"; do if [[ -s "$file" ]]; then tail -c1 "$file" | read -r _ || echo >> "$file"; fi; done' --
      language: system
      files: \.(c|h|yml|yaml|md)$
