---

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: :none
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: FALSE
  :test_file_prefix: test_

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - test/**
  :source:
    - src/**
  :include:
    - inc/**

:defines:
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback

:tools:
  # Ceedling defaults to using gcc for compiling, linking, etc.

:plugins:
  :enabled:
    - module_generator
